org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.41-beta

mod_id=time_capsule
mod_name=Time Capsule
mod_license=MIT License
mod_version=1.0.0-indev
mod_group_id=net.mrqx.timecapsule
mod_file_name=Time Capsule
